### ISSUE TITLE
Exclude multiple parameters

### ISSUE THREAD

**Issue by adisakshya** [maxdome/swagger-combine#111]
Is there any way to exclude/include multiple parameters?
Like this;
```
apis:
  - url: 'http://<HOST>/<SOME_PATH>'
    paths:
      parameters:
        include:
          "/abc": ["parameter1", "parameter2"]
```
Obviously this doesn't work!
