### ISSUE TITLE
Root level extensions excluded from merged file

### ISSUE THREAD

**Issue by surfsoft** [maxdome/swagger-combine#117]
OpenAPI supports extension points at a numbed of locations within an OpenAPI specification (see [the docs at swagger.io](https://swagger.io/docs/specification/openapi-extensions/) for further details.

I've a pair of OpenAPI files, both with extensions at the operation level, and also at the root level. The root level extensions look something like this:

File 1:
```
x-myext-api
  service1:
    publish: true
    name: "Service 1"
```

File 2:
```
x-myext-api
  service2:
    publish: false
```

What I was hoping for was for swagger-combine to produce was this:
```
x-myext-api
  service1:
    publish: true
    name: "Service 1"
  service2:
    publish: false
```
What actually happens is that no part of either extension is included. My extensions at the operation level are carried through correctly.

Unsure if this is a bug, or should be classified as a feature request.
